import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Check, Loader2, Copy, Download, RefreshCw, FileText, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";

export const Route = createFileRoute("/app/prd")({
  component: PRDPage,
});

const STEPS = [
  "Menganalisis Ide",
  "Menyusun Requirement",
  "Menentukan Fitur",
  "Menyusun User Flow",
  "Membuat Business Rule",
  "Menyusun Arsitektur",
  "Menyelesaikan Dokumen PRD",
];

const PRD_TEXT = `# PRD — Marketplace UMKM Nusantara

## 1. Ringkasan
Platform marketplace yang menghubungkan UMKM lokal dengan pembeli...

## 2. Tujuan
- Meningkatkan akses pasar UMKM
- Memberikan pengalaman belanja yang mudah
- Otomatisasi manajemen pesanan

## 3. Target Pengguna
- Pembeli individu
- Penjual UMKM
- Admin platform

## 4. Fitur Utama
1. Autentikasi & Profil
2. Katalog Produk & Kategori
3. Keranjang & Checkout
4. Pembayaran (Payment Gateway)
5. Manajemen Pesanan
6. Dashboard Penjual & Admin
7. Notifikasi Real-time
8. Ulasan & Rating

## 5. User Flow
Login → Browse Produk → Tambah ke Keranjang → Checkout → Pembayaran → Konfirmasi

## 6. Business Rules
- Komisi platform 5% per transaksi
- Refund otomatis jika pesanan tidak diproses dalam 24 jam

## 7. Arsitektur
- Frontend: React + TanStack Router
- Backend: Node.js + PostgreSQL
- Deployment: Cloudflare + Vercel
`;

function PRDPage() {
  const navigate = useNavigate();
  const [step, setStep] = useState(0);
  const [done, setDone] = useState(false);

  useEffect(() => {
    if (done) return;
    const t = setTimeout(() => {
      if (step < STEPS.length - 1) setStep((s) => s + 1);
      else setDone(true);
    }, 600);
    return () => clearTimeout(t);
  }, [step, done]);

  if (!done) {
    return (
      <div className="flex min-h-screen items-center justify-center px-6">
        <div className="w-full max-w-lg">
          <div className="mb-8 text-center">
            <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/15 text-primary">
              <Loader2 className="h-6 w-6 animate-spin" />
            </div>
            <h1 className="mt-6 text-2xl font-semibold">Menghasilkan PRD...</h1>
            <p className="mt-2 text-sm text-muted-foreground">
              AI sedang menganalisis kebutuhan aplikasi Anda
            </p>
          </div>
          <div className="mb-6">
            <Progress value={((step + 1) / STEPS.length) * 100} className="h-1.5" />
          </div>
          <div className="card-premium p-6">
            <div className="space-y-3">
              {STEPS.map((s, i) => (
                <div key={s} className="flex items-center gap-3 text-sm">
                  <div
                    className={
                      i < step
                        ? "text-primary"
                        : i === step
                          ? "text-primary"
                          : "text-muted-foreground/40"
                    }
                  >
                    {i < step ? (
                      <Check size={16} />
                    ) : i === step ? (
                      <Loader2 size={16} className="animate-spin" />
                    ) : (
                      <div className="h-4 w-4 rounded-full border border-current" />
                    )}
                  </div>
                  <span className={i <= step ? "text-foreground" : "text-muted-foreground"}>
                    {s}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl px-6 py-10">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/15 text-primary">
            <FileText size={18} />
          </div>
          <div>
            <h1 className="text-xl font-semibold">Product Requirement Document</h1>
            <p className="text-xs text-muted-foreground">Generated by AI · Draft v1</p>
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button variant="outline" size="sm" onClick={() => { navigator.clipboard.writeText(PRD_TEXT); toast.success("Disalin"); }}>
            <Copy className="mr-2 h-4 w-4" /> Copy
          </Button>
          <Button variant="outline" size="sm"><Download className="mr-2 h-4 w-4" /> Markdown</Button>
          <Button variant="outline" size="sm"><Download className="mr-2 h-4 w-4" /> PDF</Button>
          <Button variant="outline" size="sm" onClick={() => { setStep(0); setDone(false); }}>
            <RefreshCw className="mr-2 h-4 w-4" /> Generate Ulang
          </Button>
          <Button size="sm" onClick={() => navigate({ to: "/app/tasks" })}>
            Lanjut ke Task <ArrowRight className="ml-2 h-4 w-4" />
          </Button>
        </div>
      </div>

      <div className="card-premium p-8">
        <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-foreground/90">
          {PRD_TEXT}
        </pre>
      </div>
    </div>
  );
}
